version: '3'
services:
  nemoService:
    container_name: nemo
    image: yunxindev/nemo-api:1.0
    environment:
      APPKEY: ${APPKEY} # 添加云信appkey
      APPSECRET: ${APPSECRET} # 添加云信APPSECRET
      SUD_APPID: ${SUD_APPID} # 忽然游戏appId
      SUD_APPKEY: ${SUD_APPKEY} # 忽然游戏appKey
      SUD_APPSECRET: ${SUD_APPSECRET} # 忽然游戏APPSECRET
    volumes:
      - ./data/nemoService/:/data
    networks:
      - test_network
    ports:
      - "9981:9981"
    depends_on:
      - redis
      - mysql
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/redis.conf:/etc/redis/redis.conf
      - ./data/redis/data:/data
    networks:
      - test_network
    command: redis-server /etc/redis/redis.conf

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'nemo'
      MYSQL_USER: 'nemo'
      MYSQL_PASSWORD: '123456'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/db:/var/lib/mysql
      - ./data/mysql/conf/my.cnf:/etc/mysql/conf.d
      - ./data/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - test_network
    command: --default-authentication-plugin=mysql_native_password

networks:
  test_network: