spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
      minimum-idle: 2
      connection-test-query: SELECT 1
      login-timeout: 30000
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      maximum-pool-size: 100
      max-lifetime: 900000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://mysql:3306/nemo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: 'nemo'
    password: '123456'
  redis:
    database: 0
    host: redis
    port: 6379  #可不配，因为底层默认值为6379
    pool:
      max-active: 100 #连接池最大连接数（负值表示没有限制）
      max-wait: 3000 #连接池最大阻塞等待时间（负值表示没有限制）
      max-idle: 200 #连接池最大空闭连接数
      min-idle: 50 #连接汉最小空闲连接数
      timeout: 600 #连接超时时间（毫秒）

yunxin:
  origin:
    appKey: ${APPKEY} # 云信appkey,如果需要申请应用可联系商务
    appSecret: ${APPSECRET} # 云信appSecret
    nimHost: https://api.netease.im
    neRoomHost: https://roomkit.netease.im/
    securityAuditHost: https://logic-dev.netease.im/
    rtcHost: https://logic-dev.netease.im/
business:
  yunxinAssistAccid: yunxinassistaccid_1 #云信派对小助手
  systemAccid: nimsystembot_1  #服务端系统Nim账号
  1v1RtcRoomLiveTime: 10 # 单位（分钟） 1v1RTC房间存活时间，demo默认10分钟回收房间
  voiceRoomConfigId: 569 # 语聊房模板

server:
  port: 9981
